server:
  port: 7001
  servlet:
    context-path: /auth

spring:
  # redis 数据库配置
  redis:
    host: 192.168.127.110
    port: 6379

  # 数据源配置
  datasource:
    #mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.127.110:3306/advp_auth?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
    #   数据源其他配置, 在 DruidConfig配置类中手动绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL

logging:
  level:
    com.alibaba.nacos.client.config.impl: WARN